/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Shell via UART communication
 * \abstract A Shell is used to parse a command line and call the corresponding command execution. The ASCLIN module is used to interface with the Shell through the USB port via UART.
 * \description The ASCLIN module is configured for UART communication.
 *              The Shell from iLLDs exploits the ASCLIN module to interpret and manage commands from the
 *              user like "info", "toggle [x]" or "help".
 *
 * \name shell
 * \version V1.0.2
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \board APPLICATION KIT TC2x5 V2.0, KIT_AURIX_TC275_TFT-CA-Step, TC27xTP_D-Step
 * \keywords ASC, ASCLIN_Shell_UART_1, AURIX, UART, VCOM, serial communication, shell
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ASCLIN_Shell_UART.h"
#include "IfxAsclin_Asc.h"

#include "ticks.h"
#include "led.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
extern IfxStdIf_DPipe g_ascStandardInterface;

int core0_main(void)
{
    uint32_t jtag_id = MODULE_CBS.JTAGID.U;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    SystemCoreClockUpdate();
    // Initialize ticks system (pass 0 to auto-detect clock speed)
    ticks_init(0);

    /* Initialize the Shell Interface and the UART communication */
    initShellInterface();

    while(1)
    {
        delay_ticks(400);

//        runShellInterface(); /* Run the application shell */
        IfxStdIf_DPipe_print(&g_ascStandardInterface, "%u %08X %u\n", SystemCoreClock, jtag_id, get_tick_count());

        LED1_Toggle();
        delay_ticks(400);
        LED2_Toggle();
        delay_ticks(400);
        LED3_Toggle();
        delay_ticks(400);
        LED4_Toggle();
        delay_ticks(400);
    }
    return (1);
}

