/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ASCLIN_Shell_UART.h"
#include "IfxAsclin_Asc.h"

#include "ticks.h"
#include "led.h"
#include "dhry.h"
#include "shared_tokens.h"

extern IfxStdIf_DPipe g_ascStandardInterface;

extern void Proc_5 (void);

extern IfxCpu_syncEvent g_cpuSyncEvent;

int core2_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    uint32_t jtag_id = MODULE_CBS.JTAGID.U;
    uint32 core_id = (uint32)IfxCpu_getCoreId();

    uint32_t i_core_id = 0;
    uint32_t i_cpu_id = 0;
    get_raw_core_info(&i_core_id, &i_cpu_id);

    while(1) {
        WAIT_FOR_MY_TURN(2);

        PRINTF("%u core:%08X \n cpu:%08X %08X\n", SystemCoreClock, i_core_id, i_cpu_id, jtag_id);

        dhry_main(SystemCoreClock);

        delay_ticks(400);

//        runShellInterface(); /* Run the application shell */
        PRINTF("core:%u ends\n", i_core_id);

        LED1_Toggle();
        delay_ticks(400);
        LED2_Toggle();
        delay_ticks(400);
        LED3_Toggle();
        delay_ticks(400);
        LED4_Toggle();
        delay_ticks(4000);

        // --- Pass token to Core0 ---
        g_activeCoreToken = 0;
    }
    return (1);
}
