/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Shell via UART communication
 * \abstract A Shell is used to parse a command line and call the corresponding command execution. The ASCLIN module is used to interface with the Shell through the USB port via UART.
 * \description The ASCLIN module is configured for UART communication.
 *              The Shell from iLLDs exploits the ASCLIN module to interpret and manage commands from the
 *              user like "info", "toggle [x]" or "help".
 *
 * \name shell
 * \version V1.0.2
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \board APPLICATION KIT TC2x5 V2.0, KIT_AURIX_TC275_TFT-CA-Step, TC27xTP_D-Step
 * \keywords ASC, ASCLIN_Shell_UART_1, AURIX, UART, VCOM, serial communication, shell
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "ASCLIN_Shell_UART.h"
#include "IfxAsclin_Asc.h"

#include "ticks.h"
#include "led.h"
#include "core_portme.h"
#include "shared_tokens.h"
#include "buzzer.h"
#include "dts.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
extern IfxStdIf_DPipe g_ascStandardInterface;

Buzzer_Driver myBuzzer;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    SystemCoreClockUpdate();
    // Initialize ticks system (pass 0 to auto-detect clock speed)
    ticks_init(0);

    /* Initialize the Shell Interface and the UART communication */
    initShellInterface();

    uint32_t jtag_id = MODULE_CBS.JTAGID.U;
    uint32 core_id = (uint32)IfxCpu_getCoreId();

    uint32_t i_core_id = 0;
    uint32_t i_cpu_id = 0;
    get_raw_core_info(&i_core_id, &i_cpu_id);

    /* Initialize the buzzer driver specifically on Pin P33.0 */
    Buzzer_init(&myBuzzer, &IfxGtm_ATOM2_4_TOUT22_P33_0_OUT);

    const uint32_t FLASH_SIZE_TABLE_KB[]={256, 512, 1024, 1536, 2048, 2560, 3072, 4096, 5120, 1024*6, 1024*7, 1024*8};
    while(1) {
        WAIT_FOR_MY_TURN(0);

        PRINTF("CHIPID:%X %c step  AurixGen:%u EmuDevice?%s Flash SIZE:%u KB HSM:%s SpeedGrade:%X FlashVer:%X\n",
                        MODULE_SCU.CHIPID.B.CHID,
                        (MODULE_SCU.CHIPID.B.CHREV/0x10)+'A',
                        MODULE_SCU.CHIPID.B.CHTEC,
                        (MODULE_SCU.CHIPID.B.EEA==1)?"Yes":"No",
                        FLASH_SIZE_TABLE_KB[MODULE_SCU.CHIPID.B.FSIZE%0x0c],
                        (MODULE_SCU.CHIPID.B.SEC==1)?"Yes":"No",
                        MODULE_SCU.CHIPID.B.SP,
                        MODULE_SCU.CHIPID.B.UCODE
                );

        PRINTF("DEPT:%s, MANUF:%s\n",
                        (0==MODULE_SCU.MANID.B.DEPT)?"ATV Microcontroller department":"Unknown",
                        (0xc1==MODULE_SCU.MANID.B.MANUF)?"Infineon Technologies":"Unknown"
                );

        Ifx_CPU_DCON2 tmp_dcon2;
        tmp_dcon2.U = __mfcr( CPU_DCON2 );
        PRINTF("Data Cache Size:%u KB, Data Scratch Size:%u KB\n",
                tmp_dcon2.B.DCACHE_SZE,
                tmp_dcon2.B.DSCRATCH_SZE);

        PRINTF("%u core:%u \n cpu:%08X %08X\n", SystemCoreClock, i_core_id, i_cpu_id, jtag_id);

        /* Play a 2.048 kHz tone at increasing volume */
        Buzzer_setTone(&myBuzzer, 2048, 10);

        delay_ticks(6000);
        Buzzer_stop(&myBuzzer);

        Buzzer_setTone(&myBuzzer, 2048, 40);
        delay_ticks(6000);
        Buzzer_stop(&myBuzzer);

        Buzzer_setTone(&myBuzzer, 2048, 90);
        delay_ticks(6000);
        Buzzer_stop(&myBuzzer);

        // 4. Read Temperature Sensor
        start_dts_measure();
        float32 chip_temp = read_dts_celsius();

        PRINTF("Current Die: %.2f C\n", chip_temp);

        coremark_main();

        delay_ticks(400);

//        runShellInterface(); /* Run the application shell */
        PRINTF("core:%u ends\n", i_core_id);

        LED1_Toggle();
        delay_ticks(400);
        LED2_Toggle();
        delay_ticks(2000);

        // --- Pass token to Core1 ---
        g_activeCoreToken = 1;
    }
    return (1);
}

